version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-notas
    environment:
      POSTGRES_DB: notas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-notas
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: notas_db
      DB_USER: admin
      DB_PASSWORD: admin123
    stdin_open: true
    tty: true
